import pandas as pd
import numpy as np


def calculate_savings(row):
    power_kw = 11  # Standard charging speed for a German home/office Wallbox
    energy_needed = row["energy_needed_kwh"]

    # Define electricity prices: Expensive (0.40€) during peak hours (17:00-21:00),
    # otherwise cheap (0.22€).
    prices = {h: (0.40 if 17 <= h <= 21 else 0.22) for h in range(24)}

    # --- BEHAVIOR 1: DUMB CHARGING ---
    # Logic: Start charging immediately upon arrival until the battery is full.
    arrival_h = row["arrival"].hour
    dumb_cost = 0
    temp_e_dumb = energy_needed
    h = arrival_h
    while temp_e_dumb > 0:
        # Calculate cost for this specific hour based on the price at that time
        dumb_cost += min(temp_e_dumb, power_kw) * prices[h % 24]
        temp_e_dumb -= power_kw
        h += 1

    # --- BEHAVIOR 2: SMART CHARGING ---
    # Logic: Look at all hours the car is parked and pick the cheapest ones first.
    duration = int((row["departure"] - row["arrival"]).total_seconds() // 3600)

    # Collect all price points available during the parking window and sort them
    available = sorted([prices[(arrival_h + i) % 24] for i in range(duration)])

    smart_cost = 0
    temp_e_smart = energy_needed
    for price in available:
        if temp_e_smart <= 0:
            break
        energy_step = min(temp_e_smart, power_kw)
        smart_cost += energy_step * price
        temp_e_smart -= energy_step

    # Return both results to be added to the main table
    return pd.Series([round(dumb_cost, 2), round(smart_cost, 2)])


## --- MAIN EXECUTION ---
try:
    # STEP 1: Load the raw data generated by the first script (data_gen.py)
    df = pd.read_csv("fleet_data.csv", parse_dates=["arrival", "departure"])

    # STEP 2: Run the optimization function for every row (every car) in the table
    results = df.apply(calculate_savings, axis=1)

    # STEP 3: Assign the results to new columns in our DataFrame
    df["dumb_cost_eur"] = results[0]
    df["smart_cost_eur"] = results[1]

    # STEP 4: Calculate the final 'Savings' column (The key for our charts!)
    df["savings_eur"] = df["dumb_cost_eur"] - df["smart_cost_eur"]

    # STEP 5: Save to a NEW file. Streamlit reads THIS file to display the dashboard.
    df.to_csv("fleet_data_optimized.csv", index=False)

    # STEP 6: Print success messages to the terminal for debugging
    print(" Optimized file saved successfully!")
    print(f" Total Savings found: {df['savings_eur'].sum():.2f} EUR")

except Exception as e:
    # If the file is missing or code crashes, show the error in the terminal
    print(f"Error during optimization: {e}")
